<?php
$backgrounds = [
	[
		'image' => 'P1060292_min.jpg',
		'alpha' => 0.8,
		'desktop-position' => '55% 35%',
		'desktop-size' => 'cover',
		'mobile-position' => '50% -400px',
		'mobile-size' => 'cover',
		'attribution' => 'Mersh [<a href="https://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>], <a href="https://commons.wikimedia.org/wiki/File:P1060292_min.jpg">via Wikimedia Commons</a>',
	],
	[
		'image' => 'TNFSH_Small_Assembly_Hall(mersh_edition001).jpg',
		'alpha' => 0.8,
		'desktop-position' => '55% 70%',
		'desktop-size' => 'cover',
		'mobile-position' => '40% -1000px',
		'mobile-size' => 'cover',
		'attribution' => 'Mersh [<a href="https://creativecommons.org/licenses/by-sa/3.0">CC BY-SA 3.0</a>], <a href="https://commons.wikimedia.org/wiki/File:TNFSH_Small_Assembly_Hall(mersh_edition001).jpg">via Wikimedia Commons</a>',
	],
	[
		'image' => 'Square_of_tnfsh000.jpg',
		'alpha' => 0.8,
		'desktop-position' => '55% 60%',
		'desktop-size' => 'cover',
		'mobile-position' => '47% -480px',
		// 'mobile-position' => '90% -600px',
		'mobile-size' => '100% auto',
		'attribution' => 'Mersh [<a href="https://creativecommons.org/licenses/by-sa/3.0">CC BY-SA 3.0</a>], <a href="https://commons.wikimedia.org/wiki/File:Square_of_tnfsh000.jpg">via Wikimedia Commons</a>',
	],
	[
		'image' => 'TNFSH_the_Red_Building_-_inside_the_campus.jpg',
		'alpha' => 0.8,
		'desktop-position' => '55% 60%',
		'desktop-size' => 'cover',
		'mobile-position' => '43% -900px',
		'mobile-size' => 'cover',
		'attribution' => '張家榮 ; [<a href="https://creativecommons.org/licenses/by/2.0">CC BY 2.0</a>], <a href="https://commons.wikimedia.org/wiki/File:TNFSH_the_Red_Building_-_inside_the_campus.jpg">via Wikimedia Commons</a>',
	],
	[
		'image' => 'TNFSH003.jpg',
		'alpha' => 0.7,
		'desktop-position' => '55% 60%',
		'desktop-size' => 'cover',
		'mobile-position' => '62% -1000px',
		'mobile-size' => 'cover',
		'attribution' => 'Mersh [<a href="https://creativecommons.org/licenses/by-sa/3.0">CC BY-SA 3.0</a>], <a href="https://commons.wikimedia.org/wiki/File:TNFSH003.jpg">via Wikimedia Commons</a>',
	],
	[
		'image' => '1280px-TNFSH_Side_Entrance.JPG',
		'alpha' => 0.7,
		'desktop-position' => '55% 20%',
		'desktop-size' => 'cover',
		'mobile-position' => '90% -420px',
		'mobile-size' => 'cover',
		'attribution' => 'I, <a href="/wiki/User:KevinAction" title="User:KevinAction">KevinAction</a> [<a href="http://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>], <a href="https://commons.wikimedia.org/wiki/File:TNFSH_Side_Entrance.JPG">via Wikimedia Commons</a>',
	],
];
